# This file contains values from Cookiecutter

default_context:
  project_name: "autostory"
  project_description: "Awesome `autostory` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "autostory"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "peterlau123"
  email: "liuxin_signal@163.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
